"""add plugin and secret tables

Revision ID: 1e981ca9aee9
Revises: e05d167d7e6a
Create Date: 2026-02-24 05:50:29.541983

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e981ca9aee9"
down_revision: Union[str, Sequence[str], None] = "e05d167d7e6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin", sa.Column("config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plugin", "config")
    # ### end Alembic commands ###
