"""hybrid_store

Revision ID: 24b3e7c15c7d
Revises: 1e981ca9aee9
Create Date: 2026-02-27 00:07:45.061901

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24b3e7c15c7d"
down_revision: Union[str, Sequence[str], None] = "1e981ca9aee9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin", sa.Column("manifest_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "plugin", sa.Column("required_role", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="user")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plugin", "required_role")
    op.drop_column("plugin", "manifest_id")
    # ### end Alembic commands ###
