"""add_groups

Revision ID: 82e132bea019
Revises: 8cfbcbd75523
Create Date: 2026-02-28 09:08:07.014988

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82e132bea019"
down_revision: Union[str, Sequence[str], None] = "8cfbcbd75523"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plugin", sa.Column("allowed_groups", sa.JSON(), nullable=True))
    op.add_column("user", sa.Column("groups", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "groups")
    op.drop_column("plugin", "allowed_groups")
    # ### end Alembic commands ###
