"""hybrid_store

Revision ID: 8cfbcbd75523
Revises: 24b3e7c15c7d
Create Date: 2026-02-27 00:14:03.306927

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8cfbcbd75523"
down_revision: Union[str, Sequence[str], None] = "24b3e7c15c7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
