"""add_llm_trace

Revision ID: a42cd2621fdf
Revises: 82e132bea019
Create Date: 2026-03-01 13:19:35.193890

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a42cd2621fdf"
down_revision: Union[str, Sequence[str], None] = "82e132bea019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_trace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_summary", sa.Text(), nullable=True),
        sa.Column("response_summary", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("tools_bound", sa.JSON(), nullable=True),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("routing_queries", sa.JSON(), nullable=True),
        sa.Column("matched_tools", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_trace_session_id"), "llm_trace", ["session_id"], unique=False)
    op.create_index(op.f("ix_llm_trace_trace_id"), "llm_trace", ["trace_id"], unique=False)
    op.create_index(op.f("ix_llm_trace_user_id"), "llm_trace", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_trace_user_id"), table_name="llm_trace")
    op.drop_index(op.f("ix_llm_trace_trace_id"), table_name="llm_trace")
    op.drop_index(op.f("ix_llm_trace_session_id"), table_name="llm_trace")
    op.drop_table("llm_trace")
    # ### end Alembic commands ###
