"""add plugin and secret tables

Revision ID: e05d167d7e6a
Revises: a1b2c3d4e5f7
Create Date: 2026-02-24 13:43:47.681392

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e05d167d7e6a"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plugin_name"), "plugin", ["name"], unique=False)
    op.create_index(op.f("ix_plugin_status"), "plugin", ["status"], unique=False)
    op.create_table(
        "secret",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("encrypted_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope", sa.Enum("global_scope", "user_scope", name="secretscope"), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("plugin_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plugin_id"], ["plugin.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_secret_key"), "secret", ["key"], unique=False)
    op.alter_column("memory", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("memory_user_id_fkey"), "memory", type_="foreignkey")
    op.create_foreign_key(None, "memory", "user", ["user_id"], ["id"], ondelete="CASCADE")
    op.alter_column("user_identities", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("user_identities_user_id_fkey"), "user_identities", type_="foreignkey")
    op.create_foreign_key(None, "user_identities", "user", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_identities", type_="foreignkey")
    op.create_foreign_key(op.f("user_identities_user_id_fkey"), "user_identities", "user", ["user_id"], ["id"])
    op.alter_column("user_identities", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(None, "memory", type_="foreignkey")
    op.create_foreign_key(op.f("memory_user_id_fkey"), "memory", "user", ["user_id"], ["id"])
    op.alter_column("memory", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("ix_secret_key"), table_name="secret")
    op.drop_table("secret")
    op.drop_index(op.f("ix_plugin_status"), table_name="plugin")
    op.drop_index(op.f("ix_plugin_name"), table_name="plugin")
    op.drop_table("plugin")
    # ### end Alembic commands ###
