"""add session_summary

Revision ID: e8b19c2d3f4a
Revises: f8a2c3d4e5f6
Create Date: 2026-02-11 14:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8b19c2d3f4a'
down_revision: Union[str, None] = 'f8a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table('sessionsummary',
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('start_msg_id', sa.Integer(), nullable=False),
    sa.Column('end_msg_id', sa.Integer(), nullable=False),
    sa.Column('msg_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessionsummary_session_id'), 'sessionsummary', ['session_id'], unique=False)
    op.add_column('sessionmessage', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('sessionmessage', 'is_archived')
    op.drop_index(op.f('ix_sessionsummary_session_id'), table_name='sessionsummary')
    op.drop_table('sessionsummary')
    # ### end Alembic commands ###
