"""Add MemorySkill and MemorySkillChangelog tables

Revision ID: f9c2d3e4a5b6
Revises: e8b19c2d3f4a
Create Date: 2026-02-13 07:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9c2d3e4a5b6"
down_revision: Union[str, None] = "e8b19c2d3f4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table(
        "memoryskill",
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_base", sa.Boolean(), nullable=False),
        sa.Column("source_file", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("positive_count", sa.Integer(), nullable=False),
        sa.Column("negative_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memoryskill_name"), "memoryskill", ["name"], unique=True)
    op.create_index(op.f("ix_memoryskill_skill_type"), "memoryskill", ["skill_type"], unique=False)

    op.create_table(
        "memoryskillchangelog",
        sa.Column("old_prompt", sa.Text(), nullable=True),
        sa.Column("new_prompt", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("skill_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["memoryskill.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memoryskillchangelog_skill_id"), "memoryskillchangelog", ["skill_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f("ix_memoryskillchangelog_skill_id"), table_name="memoryskillchangelog")
    op.drop_table("memoryskillchangelog")
    op.drop_index(op.f("ix_memoryskill_skill_type"), table_name="memoryskill")
    op.drop_index(op.f("ix_memoryskill_name"), table_name="memoryskill")
    op.drop_table("memoryskill")
    # ### end Alembic commands ###
