from datetime import datetime
from typing import Optional

from sqlalchemy import Column, Text
from sqlmodel import Field, SQLModel


class Session(SQLModel, table=True):
    """
    Represents a conversational session.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    session_uuid: str = Field(index=True, unique=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    title: Optional[str] = Field(default=None)

    # Status flags
    active: bool = Field(default=True)

    # Goal/Summary generated by LLM (Future Phase)
    summary: Optional[str] = Field(sa_column=Column(Text, nullable=True))

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class SessionMessage(SQLModel, table=True):
    """
    Represents a specific message within a session.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="session.id", index=True)

    # Message Logic
    role: str  # user, assistant, system, tool
    type: str  # human, ai, tool, system

    # Content sent to LLM (potentially pruned)
    content: str = Field(sa_column=Column(Text, nullable=False))

    # Tool Specifics
    tool_call_id: Optional[str] = Field(default=None, index=True)
    tool_name: Optional[str] = None

    # Metadata
    token_count: int = Field(default=0)
    is_pruned: bool = Field(default=False)  # If True, 'content' is a summary

    # Debugging: Original full content (optional, for auditing big responses)
    # We might not store this for very large blobs to save space, but useful for now.
    original_content: Optional[str] = Field(sa_column=Column(Text, nullable=True))

    created_at: datetime = Field(default_factory=datetime.utcnow)
